[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = []

[variables]
NODE_ENV = 'production'

[build]
workingDir = './backend'

[install]
workingDir = './backend'

[start]
cmd = 'npm start'
workingDir = './backend'